#
# Copyright 2019-2022 Signal Messenger, LLC
# SPDX-License-Identifier: AGPL-3.0-only
#

[workspace]
members = [
    "backend",
    "common",
    "frontend",
]

[profile.release]
debug = 1
panic = "abort"
lto = "fat"
codegen-units = 1
