# https://docs.rs/crate/cargo-audit/0.14.1/source/audit.toml.example

[output]
deny = ["unmaintained", "unsound", "yanked"]
quiet = false

[advisories]
ignore = [
    "RUSTSEC-2021-0119" # Ignore advisory for nix (dependency of psutil); getgrouplist is not used.
]
